safe:
  - anyio
  - certifi
  - charset-normalizer
  - graphene
  - graphql-core
  - graphql-relay
  - idna
  - itsdangerous
  - jinja2
  - markupsafe
  - promise
  - python-multipart
  - pyyaml
  - requests
  - six
  - sniffio
  - starlette
  - urllib3
